version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_jp
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tweeet
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      LANG: ja_JP.utf8
      LC_ALL: ja_JP.UTF-8
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306